[General]
TcpServerPort = 5760
ReportStats = false
MavlinkDialect = common

[UartEndpoint pixhawk]
Device = /dev/ttyACM0
Baud = 115200

[UdpEndpoint qgc_netbird]
Mode = Normal
Address = GROUND_STATION_NETBIRD_IP
Port = 14550
